 const phrases = {
    1: "El número uno",
    2: "La pareja, los patitos",
    3: "La tercia",
    4: "La cuarta",
    5: "La mano, la quina",
    6: "La media docena, la docena chica",
    7: "La suerte, la siete",
    8: "El cacho, la doble cuatro",
    9: "La ternera",
    10: "El diez, la decena",
    11: "La once prima",
    12: "La docena grande",
    13: "La mala suerte, el martes y trece",
    14: "La niña bonita, el enano",
    15: "La quinceañera, la niña bonita grande",
    16: "La dulce dieciséis",
    17: "La empanada, la docena y cinco",
    18: "La mayoría de edad",
    19: "El buen vino",
    20: "La veintena",
    21: "La mayoría de edad",
    22: "Los patos, los patitos y un huevo",
    23: "La viuda",
    24: "La docena y media, el dos por uno",
    25: "La mano de póker",
    26: "La mitad de la docena chica",
    27: "El cojín, el cordero",
    28: "La rosa",
    29: "La docena y media grande",
    30: "La tres decenas",
    31: "El valiente",
    32: "La treintaidos",
    33: "La treintaitrés",
    34: "La treintaicuatro",
    35: "La silla",
    36: "La treintaiseis",
    37: "La treintaisiete",
    38: "La treintaocho",
    39: "La bomba",
    40: "La cuarentena",
    41: "La cuarenta y uno",
    42: "La cuarentaidos",
    43: "La cuarentaitrés",
    44: "La cuarentaicuatro",
    45: "La mitad de noventa",
    46: "La cuarentaiseis",
    47: "La cuarentaisiete",
    48: "La cuarentaocho",
    49: "La cuarenta y nueve",
    50: "La mitad del siglo",
    51: "El payaso, el pinto",
    52: "La cincuentaidos",
    53: "La cincuenta y tres",
    54: "La cincuenta y cuatro",
    55: "La mano de la abuela",
    56: "La cincuentaiseis",
    57: "La cincuentaisiete",
    58: "La cincuentaocho",
    59: "La cincuenta y nueve",
    60: "La edad de jubilación",
    61: "La calle, la diosa",
    62: "La sesentaidos",
    63: "La jubilación",
    64: "La sesentaiseis",
    65: "La sesentaisiete",
    66: "La sesentaocho",
    67: "La posición del kamasutra",
    68: "La septuagenaria",
    69: "La vieja y el galán",
    70: "La setentaidos",
    71: "La setenta y tres",
    72: "La setenta y cuatro",
    73: "La mano de la abuelita",
    74: "La setentaiseis",
    75: "La setentaisiete",
    76: "La setentaocho",
    77: "La setenta y nueve",
    78: "La ochentena",
    79: "La ochenta y uno",
    80: "La ochentaidos",
    81: "La ochenta y tres",
    82: "La ochenta y cuatro",
    83: "La mano de la abuela vieja",
    84: "La ochentaiseis",
    85: "La ochentaisiete",
    86: "La ochentaocho",
    87: "La ochenta y nueve",
    88: "La nonagésima, la gran mayoría",
    89: "El número máximo",
    90: "La nonagésima, la gran mayoría"

}
export { phrases };